spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/quickstay
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    include: security
  messages:
    basename: errors