spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/quickstay
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    include: security