# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: CI/CD using github actions

on:
  push:
    branches: [ "main" ]

jobs:
  CI-CD :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Generate application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.YML_PROD }}" > src/main/resources/application.yml

      - name: Generate application-security.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.YML_SECURITY }}" > src/main/resources/application-security.yml

      - name: Build with Gradle
        run: ./gradlew build
